export const pageDataTablesData = [
  {
    id: "1",
    noofjob:"80",
    position: "J0624013060",
    clientname: "Loreal",
    Brief:"BENEFIT FAN FEST ANIMATION",
    Location:"West",
    Status:"UPLOADED",
    Comment:"JPG for Approval",
    Month:"1",
    Artworker: "Thakur",
    startDate: "2011/04/25",
    salary: "$320,800",
    receivedDate: "25/05/2025",
    dueDate: "15/10/2025",
    uploadDate: "01/09/2025",
  },
  {
    id: "2",
    noofjob: "06",
    position: "J0624013070",
    clientname: "Shephora",
    age: "Shephora",
    Brief: "LP MNY",
    Location: "All",
    Status: "DONE",
    Comment: "Started working on another job",
    Month: "1",
    Artworker: "Minil",
    startDate: "2011/07/25",
    salary: "$170,750",
    receivedDate: "25/05/2025",
    dueDate: "15/10/2025",
    uploadDate: "01/09/2025",
  },
  {
    id: "3",
    name: "AMEND",
    position: "J0624013080",
    noofjob: "13",
    clientname: "Kama Ayurveda",
    Brief: "MAKE YOURSELF BLUSH ANIMATION",
    Location: "South",
    Status: "HOLD",
    Comment: "JPG for Approval",
    Month: "4",
    Artworker: "Vignesh",
    startDate: "2009/01/12",
    salary: "$86,000",
    receivedDate: "25/05/2025",
    dueDate: "15/10/2025",
    uploadDate: "01/09/2025",
  },
  {
    id: "4",
    name: "ADAPTATION",
    position: "J0624013090",
    noofjob: "5",
    clientname:"Loreal",
    Brief: "Redken",
    Location: "All",
    Status: "UPLOADED",
    Comment: "Started working on another job",
    Month: "1",
    Artworker:"Thakur",
    startDate: "2012/03/29",
    salary: "$433,060",
    receivedDate: "25/05/2025",
    dueDate: "15/10/2025",
    uploadDate: "01/09/2025",
  },
 
];

export const csDataTablesData = [
  {
    jobno:"J0624090605",
    date:"03.11.2024",
    clientName:"LOREAL KERASTASE",
    REGION:"EAST",
    VISUAL:"K TYPOGRAPHY",
    Name:"DESSANGE SALON KEMPS CORNER ",
    CITY:"MUMBAI",
    QTY:"1",
    Width: "144",
    Height: "36",
    TotalSq: "36",
    Media: "AVERY FROSTED FILM",
    LAMINATION: "MATT",
    MOUNTING: "NO MOUNTING",
    Implementation: "YES",
    SALON: "DESSANGE SALON KEMPS CORNER MUMBAI",
    DISPATCH: "",
    DEADLINE: "07.11.2024",
    Remarks: "",
    billinglocation: "EAST",

   
  },
  {
    jobno: "J0624090604",
    date: "02.09.2024",
    clientName: "LOREAL KERASTASE",
    REGION: "WEST",
    VISUAL: "K TYPOGRAPHY",
    Name: "DESSANGE SALON KEMPS CORNER ",
    CITY: "MUMBAI",
    QTY: "1",
    Width: "144",
    Height: "36",
    TotalSq: "36",
    Media: "AVERY FROSTED FILM",
    LAMINATION: "MATT",
    MOUNTING: "NO MOUNTING",
    Implementation: "YES",
    SALON: "DESSANGE SALON KEMPS CORNER MUMBAI",
    DISPATCH: "",
    DEADLINE: "02.09.2024",
    Remarks: "",
    billinglocation: "west",
  },
  {
    jobno: "J0624090603",
    date: "02.09.2024",
    clientName: "LOREAL KERASTASE",
    REGION: "WEST",
    VISUAL: "K TYPOGRAPHY",
    Name: "DESSANGE SALON KEMPS CORNER ",
    CITY: "MUMBAI",
    QTY: "1",
    Width: "144",
    Height: "36",
    TotalSq: "36",
    Media: "AVERY FROSTED FILM",
    LAMINATION: "MATT",
    MOUNTING: "NO MOUNTING",
    Implementation: "YES",
    SALON: "DESSANGE SALON KEMPS CORNER MUMBAI",
    DISPATCH: "",
    DEADLINE: "02.09.2024",
    Remarks: "",
    billinglocation: "west",
  },
  
  
];

export const productionDataTablesData = [
  {
    id: "5",
    media: "Media A",
    mediasq: "500 Sq.Ft.",
    wastage: "50 Sq.Ft.",
    wastageper: "10%",
    laminationmedia: "Gloss",
  },
  {
    id: "6",
    media: "Media B",
    mediasq: "1000 Sq.Ft.",
    wastage: "70 Sq.Ft.",
    wastageper: "7%",
    laminationmedia: "Matte",
  },
  {
    id: "7",
    media: "Media C",
    mediasq: "750 Sq.Ft.",
    wastage: "60 Sq.Ft.",
    wastageper: "8%",
    laminationmedia: "Satin",
  },
];

export const implementationDataTablesData = [
  {
    id: "8",
    date: "05/09/2024",
    jobId: "IMP001",
    clientName: "Client X",
    location: "Dallas",
    implName: "Eve Thompson",
    jobprintdate: "04/09/2024",
  },
  {
    id: "9",
    date: "06/09/2024",
    jobId: "IMP002",
    clientName: "Client Y",
    location: "Houston",
    implName: "Chris Evans",
    jobprintdate: "05/09/2024",
  },
  {
    id: "10",
    date: "07/09/2024",
    jobId: "IMP003",
    clientName: "Client Z",
    location: "Austin",
    implName: "Patricia Holmes",
    jobprintdate: "06/09/2024",
  },
];

export const deliveryDataTablesData = [
  {
    id: "11",
    date: "08/09/2024",
    jobId: "DEL001",
    clientName: "Client 1",
    location: "Miami",
    deliveryperson: "Robert James",
  },
  {
    id: "12",
    date: "09/09/2024",
    jobId: "DEL002",
    clientName: "Client 2",
    location: "Seattle",
    deliveryperson: "Sophia Wilson",
  },
  {
    id: "13",
    date: "10/09/2024",
    jobId: "DEL003",
    clientName: "Client 3",
    location: "Boston",
    deliveryperson: "Michael Brown",
  },
];


